// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqaek_YixPVzPXGszXnYfBw3kOPH4mgcM',
    appId: '1:600836623158:web:40036a814cad6253408197',
    messagingSenderId: '600836623158',
    projectId: 'talent2trophy',
    authDomain: 'talent2trophy.firebaseapp.com',
    storageBucket: 'talent2trophy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqaek_YixPVzPXGszXnYfBw3kOPH4mgcM',
    appId: '1:600836623158:android:40036a814cad6253408197',
    messagingSenderId: '600836623158',
    projectId: 'talent2trophy',
    storageBucket: 'talent2trophy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqaek_YixPVzPXGszXnYfBw3kOPH4mgcM',
    appId: '1:600836623158:ios:40036a814cad6253408197',
    messagingSenderId: '600836623158',
    projectId: 'talent2trophy',
    storageBucket: 'talent2trophy.firebasestorage.app',
    iosBundleId: 'com.example.talent2trophy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqaek_YixPVzPXGszXnYfBw3kOPH4mgcM',
    appId: '1:600836623158:ios:40036a814cad6253408197',
    messagingSenderId: '600836623158',
    projectId: 'talent2trophy',
    storageBucket: 'talent2trophy.firebasestorage.app',
    iosBundleId: 'com.example.talent2trophy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqaek_YixPVzPXGszXnYfBw3kOPH4mgcM',
    appId: '1:600836623158:windows:40036a814cad6253408197',
    messagingSenderId: '600836623158',
    projectId: 'talent2trophy',
    storageBucket: 'talent2trophy.firebasestorage.app',
  );
}
